server {
    listen 80 default_server;
    server_name _;

    root /usr/share/motioneye/htdocs;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }

    location /mjpeg {
        proxy_pass http://127.0.0.1:8081;
        proxy_set_header Host $host;
    }

    location /api {
        proxy_pass http://127.0.0.1:8765;
        proxy_set_header Host $host;
    }
}
